config/routes.rb
Cursive::Application.routes.draw do
  resources :users

  resources :musicians

  resources :projects

  resources :genres

  resources :labels

  resources :albums

  get "site/index"

  root to: 'site#index', as: 'site_index'

end

app/models/label.rb
class Label < ActiveRecord::Base
  has_many :albums
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  # GET /labels
  # GET /labels.json
  def index
    @labels = Label.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @labels }
    end
  end

  # GET /labels/1
  # GET /labels/1.json
  def show
    @label = Label.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @label }
    end
  end

  # GET /labels/new
  # GET /labels/new.json
  def new
    @label = Label.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @label }
    end
  end

  # GET /labels/1/edit
  def edit
    @label = Label.find(params[:id])
  end

  # POST /labels
  # POST /labels.json
  def create
    @label = Label.new(params[:label])

    respond_to do |format|
      if @label.save
        format.html { redirect_to @label, notice: 'Label was successfully created.' }
        format.json { render json: @label, status: :created, location: @label }
      else
        format.html { render action: "new" }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /labels/1
  # PUT /labels/1.json
  def update
    @label = Label.find(params[:id])

    respond_to do |format|
      if @label.update_attributes(params[:label])
        format.html { redirect_to @label, notice: 'Label was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1
  # DELETE /labels/1.json
  def destroy
    @label = Label.find(params[:id])
    @label.destroy

    respond_to do |format|
      format.html { redirect_to labels_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_form.html.erb
<%= form_for(@label) do |f| %>
  <% if @label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
      <% @label.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/labels/edit.html.erb
<h1>Editing label</h1>

<%= render 'form' %>

<%= link_to 'Show', @label %> |
<%= link_to 'Back', labels_path %>

app/views/labels/index.html.erb
<h1>Listing labels</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Country</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @labels.each do |label| %>
  <tr>
    <td><%= label.name %></td>
    <td><%= label.country %></td>
    <td><%= link_to 'Show', label %></td>
    <td><%= link_to 'Edit', edit_label_path(label) %></td>
    <td><%= link_to 'Destroy', label, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Label', new_label_path %>

app/views/labels/new.html.erb
<h1>New label</h1>

<%= render 'form' %>

<%= link_to 'Back', labels_path %>

app/views/labels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @label.name %>
</p>

<p>
  <b>Country:</b>
  <%= @label.country %>
</p>


<%= link_to 'Edit', edit_label_path(@label) %> |
<%= link_to 'Back', labels_path %>